//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WakaWakaLib.Tests.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WakaWakaLib.Tests.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: &quot;id&quot;,
        ///    &quot;value&quot;: &quot;value&quot;,
        ///    &quot;editor&quot;: &quot;editor&quot;,
        ///    &quot;version&quot;: &quot;version&quot;,
        ///    &quot;os&quot;: &quot;os&quot;,
        ///    &quot;last_seen&quot;: &quot;2001-01-01T00:00:00&quot;,
        ///    &quot;created_at&quot;: &quot;2001-01-01T00:00:00&quot;,
        ///  },
        ///}.
        /// </summary>
        internal static string UserAgentDataJson {
            get {
                return ResourceManager.GetString("UserAgentDataJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: [
        ///	{
        ///		&quot;id&quot;: &quot;id&quot;,
        ///		&quot;value&quot;: &quot;value&quot;,
        ///		&quot;editor&quot;: &quot;editor&quot;,
        ///		&quot;version&quot;: &quot;version&quot;,
        ///		&quot;os&quot;: &quot;os&quot;,
        ///		&quot;last_seen&quot;: &quot;2001-01-01T00:00:00&quot;,
        ///		&quot;created_at&quot;: &quot;2001-01-01T00:00:00&quot;,
        ///	},
        ///	{
        ///		&quot;id&quot;: &quot;id2&quot;,
        ///		&quot;value&quot;: &quot;value2&quot;,
        ///		&quot;editor&quot;: &quot;editor2&quot;,
        ///		&quot;version&quot;: &quot;version2&quot;,
        ///		&quot;os&quot;: &quot;os2&quot;,
        ///		&quot;last_seen&quot;: &quot;2001-01-01T00:00:00&quot;,
        ///		&quot;created_at&quot;: &quot;2001-01-01T00:00:00&quot;,
        ///	},
        ///  ]
        ///}.
        /// </summary>
        internal static string UserAgentListDataJson {
            get {
                return ResourceManager.GetString("UserAgentListDataJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;data&quot;: {
        ///    &quot;id&quot;: &quot;id&quot;,
        ///    &quot;has_premium_features&quot;: true,
        ///    &quot;display_name&quot;: &quot;display name&quot;,
        ///    &quot;full_name&quot;: &quot;full name&quot;,
        ///    &quot;email&quot;: &quot;email&quot;,
        ///    &quot;photo&quot;: &quot;photo&quot;,
        ///    &quot;email_public&quot;: true,
        ///    &quot;is_email_confirmed&quot;: true,
        ///    &quot;photo_public&quot;: true,
        ///    &quot;timezone&quot;: &quot;timezone&quot;,
        ///    &quot;last_heartbeat&quot;: &quot;2001-01-01T00:00:00&quot;,
        ///    &quot;last_plugin&quot;: &quot;last plugin&quot;,
        ///    &quot;last_plugin_name&quot;: &quot;last plugin name&quot;,
        ///    &quot;last_project&quot;: &quot;last project&quot;,
        ///    &quot;plan&quot;: &quot;plan&quot;,
        ///    &quot;username&quot;: &quot;username&quot;,
        ///  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string UserDataJson {
            get {
                return ResourceManager.GetString("UserDataJson", resourceCulture);
            }
        }
    }
}
